import Header from "@/src/components/main/how-it-wotks/Header";
import Item from "@/src/components/main/how-it-wotks/Item";
import { Link } from "@/src/i18n/navigation";
import { Metadata } from "next";
import { BiCalendarEvent, BiCategoryAlt, BiSearch } from "react-icons/bi";
import { BsArrowRight } from "react-icons/bs";
import {
  FaCalendarAlt,
  FaCalendarCheck,
  FaCheckCircle,
  FaCreditCard,
  FaCrown,
  FaFileUpload,
  FaRegCalendarCheck,
  FaRocket,
  FaSearch,
  FaStore,
  FaUserCheck,
} from "react-icons/fa";

import { FaUserPlus, FaUsers } from "react-icons/fa6";
import { FaUser } from "react-icons/fa6";
import { MdCheckCircleOutline } from "react-icons/md";
import { PiShieldCheck } from "react-icons/pi";
import { TbStars } from "react-icons/tb";

export const metadata: Metadata = {
  title: "how it works",
  description: "Generated by create next app",
};

export default function Page() {
  const data = [
    {
      icon: FaSearch,
      title: "Discover Salons",
      number: 1,
      desc: "Find top-rated salons near you and explore their services, reviews, photos, and ratings.",
    },
    {
      icon: FaCalendarAlt,
      title: "Choose a Service",
      number: 2,
      desc: "Select the beauty service you need and choose your preferred stylist or specialist.",
    },
    {
      icon: FaRegCalendarCheck,
      title: "Pick a Date & Time",
      number: 3,
      desc: "Choose an available date and select a convenient time slot that works best for you.",
    },

    {
      icon: FaCreditCard,
      title: "Confirm Your Booking",
      number: 5,
      desc: "Review your service, date, time, and booking details, then confirm your appointment.",
    },
    {
      icon: FaCheckCircle,
      title: "Get Your Confirmation",
      number: 6,
      desc: "Receive your booking confirmation and appointment details. You're all set!",
    },
  ];
  const data2 = [
    {
      icon: FaUserPlus,
      title: "Create Your Account",
      number: 1,
      desc: "Sign up as a salon owner and create your account to start setting up your salon.",
    },
    {
      icon: FaFileUpload,
      title: "Verify Your Salon",
      number: 2,
      desc: "Submit the required documents and business information to verify and approve your salon.",
    },
    {
      icon: FaStore,
      title: "Complete Your Profile",
      number: 3,
      desc: "Add your salon details, services, prices, working hours, photos, location, and team members.",
    },
    {
      icon: FaCrown,
      title: "Upgrade to Premium",
      number: 4,
      desc: "Unlock premium features and extra tools to grow your salon and attract more customers.",
    },
    {
      icon: FaRocket,
      title: "Publish Your Salon",
      number: 5,
      desc: "Once your salon is verified, publish your profile and make it visible to customers.",
    },
    {
      icon: FaCalendarCheck,
      title: "Receive Bookings",
      number: 6,
      desc: "Customers can discover your salon, choose a service, and book an available date and time.",
    },
  ];

  return (
    <section>
      <Header />
      <div className="container-c">
        <div className="flex flex-row justify-center -mt-6">
          <div className="flex flex-row gap-3 items-center shadow-md py-6 px-8 rounded-[10px] bg-[var(--primary)]">
            <FaUser color="var(--bg)" size={25} />
            <div className="flex flex-col">
              <h2 className="text-[var(--bg)] font-bold text-[17px]">
                For Customers
              </h2>
              <p className="text-[var(--bg)] text-[13px]">
                Book your beauty journey
              </p>
            </div>
          </div>
          <div className="flex flex-row gap-3 items-center shadow-md py-6 px-8 rounded-[10px] bg-[var(--surface)]">
            <FaUserPlus color="var(--primary)" size={25} />
            <div className="flex flex-col">
              <h2 className="text-[var(--text)] font-bold text-[17px]">
                For Salon Owners
              </h2>
              <p className="text-[var(--secondary-text)] text-[13px]">
                Grow your beauty business
              </p>
            </div>
          </div>
        </div>
        {/* for customers */}
        <section className="flex flex-col mt-14 ">
          <div className="flex flex-row gap-4">
            <div className="flex items-center w-[60px] h-[60px] justify-center bg-[var(--primary)] p-4 rounded-full">
              <FaUser color="var(--bg)" size={25} />
            </div>
            <div className="flex flex-col gap-1">
              <h2 className="text-[var(--text)] font-bold text-[28px]">
                For Customers
              </h2>
              <p className="text-[var(--secondary-text)] text-[14px]">
                Book in minutes. Enjoy every moment
              </p>
            </div>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-15  mt-10 relative">
            {/* item */}
            {data.map((i, index) => (
              <div key={index} className="relative">
                {index !== 0 && (
                  <div className="absolute w-[120px] h-[1px] bg-[var(--primary)] right-45 top-12"></div>
                )}

                <Item  data={i} />
              </div>
            ))}
          </div>
        </section>
        <div className="w-full h-[2px] mt-20 mb-10 bg-[var(--border)]"></div>
        {/* for Salon owners */}
        <section className="flex flex-col mt-14 mb-10">
          <div className="flex flex-row gap-4">
            <div className="flex items-center w-[60px] h-[60px] justify-center bg-[var(--primary)] p-4 rounded-full">
              <FaStore color="var(--bg)" size={25} />
            </div>
            <div className="flex flex-col gap-1">
              <h2 className="text-[var(--text)] font-bold text-[28px]">
                For Salon Owners
              </h2>
              <p className="text-[var(--secondary-text)] text-[14px]">
                Manage Smarter Grow Faster
              </p>
            </div>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-6 gap-15  mt-10 relative">
            {/* item */}
            {data2.map((i, index) => (
              <div key={index} className="relative">
                {index !== 0 && (
                  <div className="absolute w-[100px] h-[1px] bg-[var(--primary)] right-37 top-12"></div>
                )}

                <Item  data={i} />
              </div>
            ))}
          </div>
        </section>
        <div className="rounded-[10px] howitworks2-bg p-8 shadow-md">
          <div className="flex flex-row gap-2 items-center">
            <TbStars color="var(--champagne-gold)" size={18} />
            <h2 className="text-[var(--primary)] text-[16px] font-bold">
              Why It Works
            </h2>
            <TbStars color="var(--champagne-gold)" size={18} />
          </div>
          <h3 className="text-[var(--text)] text-[25px] font-bold mt-5">
            Every thing You need{" "}
          </h3>
          <h4 className="text-[var(--text)] text-[25px] font-bold">
            all in one place
          </h4>
          <div className="flex flex-col mt-6 gap-5">
            <li className="text-[var(--secondary-text)] text-[15px] gap-2 flex items-center">
              <MdCheckCircleOutline color="var(--primary)" size={19} />
              Easy booking in just a few taps
            </li>
            <li className="text-[var(--secondary-text)] text-[15px] gap-2 flex items-center">
              <MdCheckCircleOutline color="var(--primary)" size={19} />
              Secure payments and real-time confirmations
            </li>
            <li className="text-[var(--secondary-text)] text-[15px] gap-2 flex items-center">
              <MdCheckCircleOutline color="var(--primary)" size={19} />
              Truested salons and verified reviews
            </li>
            <li className="text-[var(--secondary-text)] text-[15px] gap-2 flex items-center">
              <MdCheckCircleOutline color="var(--primary)" size={19} />
              Seamless experience for customers and salon owners
            </li>

            <Link href={'/salons'} className="px-7 mt-8 py-3 text-[var(--surface)] 
            items-center flex gap-5 scale-100 hover:scale-105 transition-all duration-300
             rounded-[10px] bg-[var(--primary)] max-w-max">
                  Explore Salons
                  <BsArrowRight color="var(--surface)" size={18}/>
            </Link>
          </div>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-10 mt-8 mb-10">
            <div className="bg-[var(--surface) border border-[var(--border)] 
            items-center px-7 py-7 shadow-md flex gap-3 rounded-[10px]">
              <FaUsers color="var(--primary)" size={60}/>
              <div className="flex flex-col "> 
                    <strong className="text-[30px] font-bold">20K+</strong>
                    <p className="text-[var(--secondary-text)] text-[14px]">Happy Customers</p>
              </div>
            </div>
            <div className="bg-[var(--surface) border border-[var(--border)] 
            items-center px-7 py-7 shadow-md flex gap-3 rounded-[10px]">
              <PiShieldCheck color="var(--primary)" size={60}/>
              <div className="flex flex-col "> 
                    <strong className="text-[30px] font-bold">1K+</strong>
                    <p className="text-[var(--secondary-text)] text-[14px]">Verified Salons</p>
              </div>
            </div>
            <div className="bg-[var(--surface) border border-[var(--border)] 
            items-center px-7 py-7 shadow-md flex gap-3 rounded-[10px]">
              <BiCalendarEvent color="var(--primary)" size={60}/>
              <div className="flex flex-col "> 
                    <strong className="text-[30px] font-bold">50K+</strong>
                    <p className="text-[var(--secondary-text)] text-[14px]">Appointments Booked</p>
              </div>
            </div>
            <div className="bg-[var(--surface) border border-[var(--border)] 
            items-center px-7 py-7 shadow-md flex gap-3 rounded-[10px]">
              <BiCategoryAlt color="var(--primary)" size={60}/>
              <div className="flex flex-col "> 
                    <strong className="text-[30px] font-bold">10+</strong>
                    <p className="text-[var(--secondary-text)] text-[14px]">Services</p>
              </div>
            </div>
        </div>
      </div>
    </section>
  );
}
