import Header from "@/src/components/main/ui/Header";
import Article from "@/src/components/main/Article";
import Benefit from "@/src/components/main/Benefit";
import Explain from "@/src/components/main/Explain";
import PopularSalon from "@/src/components/main/PopularSalon";
import Service from "@/src/components/main/Service";
import Testimonial from "@/src/components/main/Testimonial";
import { Metadata } from "next";
import {setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
    title: "Home-SalonReserve",
    description: "Generated by create next app",
  };

export default async function Page({params} : {  params: Promise<{ locale: string }>}){
    const {locale} = await params
    setRequestLocale(locale);
    return(
      <section>
         <Header />
         <Benefit/>
         <PopularSalon/>
         <Service/>
         <Explain/>
         <Testimonial/>
         <Article/>
      </section>
       
    )
}