import Header from "@/src/components/main/ui/Header";
import Article from "@/src/components/main/Article";
import Benefit from "@/src/components/main/Benefit";
import Explain from "@/src/components/main/Explain";
import PopularSalon from "@/src/components/main/PopularSalon";
import Service from "@/src/components/main/Service";
import Testimonial from "@/src/components/main/Testimonial";
import { Metadata } from "next";
import {setRequestLocale } from "next-intl/server";
import { getCategories } from "@/src/lib/api/categories";
import getSalons from "@/src/lib/api/salons";
 

export const metadata: Metadata = {
    title: "Home-SalonReserve",
    description: "Generated by create next app",
  };

export default async function Page({params} : {  params: Promise<{ locale: string }>}){
    const {locale} = await params
    setRequestLocale(locale);

    // apis
    const services = await getCategories(locale);
    const salons = await getSalons(locale);
    return(
      <section>
         <Header locale={locale}/>
         <Benefit/>
         <PopularSalon data={salons?.data}/>
         <Service data={services?.data}/>
         <Explain/>
         <Testimonial/>
         <Article/>
       
      </section>
       
    )
}