import Benefit from "@/src/components/main/Benefit";
import PopularSalon from "@/src/components/main/PopularSalon";
import { Metadata } from "next";
import {setRequestLocale } from "next-intl/server";
export const metadata: Metadata = {
    title: "Home-SalonReserve",
    description: "Generated by create next app",
  };

export default async function Page({params} : {  params: Promise<{ locale: string }>;}){
    const {locale} = await params
    setRequestLocale(locale);
    return(
      <section>
         <Benefit/>
         <PopularSalon/>
      </section>
       
    )
}