import Header from "@/src/components/main/service/Header";
import List from "@/src/components/main/service/List";
import { getCategories } from "@/src/lib/api/categories";
import { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";

export const metadata: Metadata = {
    title: "services",
    description: "Generated by create next app",
  };

export default async function Page({params} :  {  params: Promise<{ locale: string }>}){

    const {locale} = await params
    const services = await getCategories(locale);
    setRequestLocale(locale);
    

    return(
        <section>
             <Header/>
             <List data={services?.data}/>
        </section>
    )
}