import Header from "@/src/components/main/service/Header";
import List from "@/src/components/main/service/List";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "services",
    description: "Generated by create next app",
  };

export default function Page(){
    return(
        <section>
             <Header/>
             <List/>
        </section>
    )
}