import Bnefit from "@/src/components/main/Salon/Benefit";
import Filter from "@/src/components/main/Salon/Filter";
import Header from "@/src/components/main/Salon/Header";
import NeedHelp from "@/src/components/main/Salon/NeedHelp";
import SalonList from "@/src/components/main/Salon/SalonList";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "salons",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <section className="w-full relative">
      <Header />
      <div className="container-c">
        <Bnefit />
        <div className="grid grid-cols-12 gap-8 mt-15 mb-15">
          <div className="col-span-3">
            <Filter />
          </div>
          <div className="col-span-9">
            <SalonList />
          </div>
        </div>
        <NeedHelp/>
      </div>
    </section>
  );
}
