import Bnefit from "@/src/components/main/Salon/Benefit";
import Filter from "@/src/components/main/Salon/Filter";
import Header from "@/src/components/main/Salon/Header";
import NeedHelp from "@/src/components/main/Salon/NeedHelp";
import SalonList from "@/src/components/main/Salon/SalonList";
import { getSalons } from "@/src/lib/api/salonArchive/getSalons";
import { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "salons",
  description: "Generated by create next app",
};

export default async function Page({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const salons = await getSalons(locale);

  return (
    <section className="w-full relative">
      <Header />
      <div className="container-c">
        <Bnefit />
        <div className="grid grid-cols-12 gap-8 mt-15 mb-15">
          <div className="col-span-3 hidden sm:block">
            <Suspense>
              <Filter />
            </Suspense>
          </div>
          <div className="col-span-12 sm:col-span-9">
            <Suspense>
              <SalonList data={salons?.data?.data} />
            </Suspense>
          </div>
        </div>
        <NeedHelp />
      </div>
    </section>
  );
}
