import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainProvider from "@/src/providers/MainProvider";
import NextTopLoader from 'nextjs-toploader';
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const myFont = localFont({
  src: "../src/fonts/woff/iranyekanwebmediumfanum.woff",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      dir="rtl"
      lang="en"
      className={`${myFont.className} h-full antialiased`}
    >
      <body>
        <NextTopLoader color="#C97B8B" height={4} showSpinner={false} /> 
         <MainProvider>
            {children}
         </MainProvider>
      </body>
    </html>
  );
}
