import Form from "@/src/components/auth/login/Form";
import TopNav from "@/src/components/auth/login/TopNav";
import { Link } from "@/src/i18n/navigation";
import { Metadata } from "next";
import Image from "next/image";
import { Suspense } from "react";
import { FaUserPlus } from "react-icons/fa6";

export const metadata: Metadata = {
  title: "login-account",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <section className=" bg-[#F7F5F6] ">
      <div className="flex flex-flex w-full ">
        <div className="min-h-screen w-[850px] bg-login">
        
        </div>

        <div className="w-full flex flex-row justify-start mt-20 items-center">
          <div className="bg-[var(--surface)] w-[550px]    flex mt-10 mb-10 flex-col items-center rounded-[20px]   shadow-md p-8 mt-10">
            <div className="p-6 bg-[var(--primary)]/20 max-w-max rounded-full">
              <FaUserPlus color="var(--primary)" size={40} />
            </div>
            <h1 className="text-[var(--text)] font-bold text-[30px] mt-5">
              Welcome
              <span className="text-[var(--primary)]"> Back</span>
            </h1>
            <p className="text-[var(--secondary-text)] mt-2 text-[14px]">
              Login to your account and continue your beauty journey
            </p>
            <Form />
          </div>
        </div>
      </div>
    </section>
  );
}
