import BreadCrumb from "@/src/components/admin/ui/BreadCrumb";
import Card from "@/src/components/admin/ui/Card";
import { Metadata } from "next";
import {
  FiUsers,
  FiShoppingBag,
  FiDollarSign,
  FiActivity,
} from "react-icons/fi";

export const metadata: Metadata = {
  title: "دشبورد ادمین",
  description: "Generated by create next app",
};

export default function Dashboard() {
  return (
    <section>
      <BreadCrumb title="دشبورد" activePage="دشبورد" />
      <Card>
        <div className="mb-6">
          <h2 className="text-xl font-bold text-slate-800">آمار کلی سیستم</h2>

          <p className="text-sm text-slate-500 mt-1">
            خلاصه‌ای از وضعیت امروز سیستم
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6">
          {/* Users */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 hover:shadow-lg transition-all">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500">کاربران</p>

                <h2 className="text-3xl font-bold mt-2">1,245</h2>

                <span className="text-green-600 text-sm font-medium">
                  ▲ 12% این هفته
                </span>
              </div>

              <div className="w-14 h-14 rounded-2xl bg-blue-50 text-blue-600 flex items-center justify-center">
                <FiUsers size={24} />
              </div>
            </div>
          </div>

          {/* Orders */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 hover:shadow-lg transition-all">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500">سفارش‌ها</p>

                <h2 className="text-3xl font-bold mt-2">325</h2>

                <span className="text-green-600 text-sm font-medium">▲ 8%</span>
              </div>

              <div className="w-14 h-14 rounded-2xl bg-orange-50 text-orange-600 flex items-center justify-center">
                <FiShoppingBag size={24} />
              </div>
            </div>
          </div>

          {/* Revenue */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 hover:shadow-lg transition-all">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500">درآمد</p>

                <h2 className="text-3xl font-bold mt-2">245M</h2>

                <span className="text-green-600 text-sm font-medium">
                  ▲ 22%
                </span>
              </div>

              <div className="w-14 h-14 rounded-2xl bg-green-50 text-green-600 flex items-center justify-center">
                <FiDollarSign size={24} />
              </div>
            </div>
          </div>

          {/* Visitors */}
          <div className="rounded-2xl border border-slate-200 bg-white p-5 hover:shadow-lg transition-all">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-slate-500">بازدید امروز</p>

                <h2 className="text-3xl font-bold mt-2">12.8K</h2>

                <span className="text-red-500 text-sm font-medium">▼ 3%</span>
              </div>

              <div className="w-14 h-14 rounded-2xl bg-purple-50 text-purple-600 flex items-center justify-center">
                <FiActivity size={24} />
              </div>
            </div>
          </div>
        </div>
      </Card>
    </section>
  );
}
