import TopNav from "@/src/components/auth/register/TopNav";
import { Link } from "@/src/i18n/navigation";
import { Metadata } from "next";
import Image from "next/image";
import { BsArrowRight } from "react-icons/bs";
import { FaStarOfLife, FaStoreAlt } from "react-icons/fa";
import { FaUserPlus } from "react-icons/fa6";
import { MdCheckCircle } from "react-icons/md";
import { TbStars, TbUserStar } from "react-icons/tb";


export const metadata: Metadata = {
  title: "choose your account type",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <section className="w-full min-h-screen bg-register bg-[#FCF2F4]">
      <div className="grid grid-cols-12 gap-8 ">
        <div className="col-span-3"></div>
        <div className="col-span-6 mt-30 mb-20">
          <div className=" flex gap-2 flex-col items-center">
            <div className="border border-[var(--primary)] w-max-w rounded-full py-2 px-6">
              <h1 className="flex gap-3 items-center max-w-max text-[14px] text-[var(--primary)] font-bold">
                Welcome To Our Website
                <TbStars color="var(--champagne-gold)" size={18} />
              </h1>
            </div>
            <div>
              <h2 className="text-[35px] text-center text-[var(--text)] font-bold">
                Join Our Commiunity
              </h2>
              <h3 className="text-[40px] text-center text-[var(--primary)] font-bold">
                Choose Your Account Type
              </h3>
              <p className="text-[15px] text-center mt-2 text-[var(--secondary-text)] ">
                Create an account to book appontments, manage your profile,and
                explore amazing beauty service
              </p>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-10 mt-8">
            {/* costomer section */}
            <div className="bg-[var(--surface)] p-2 rounded-[10px]">
              <div className="w-full  relative flex justify-center">
                <Image
                  src={"/images/salon.jpg"}
                  className="object-cover h-[300px] rounded-[10px]"
                  alt=""
                  width={800}
                  height={600}
                />
                <div className="absolute flex justify-center -bottom-10 w-[100px] h-[100px] rounded-full p-1 bg-[var(--surface)]">
                  <div className="bg-[var(--rose-gold)]/50 items-center flex justify-center w-[90px] h-[90px] rounded-full">
                    <TbUserStar size={50} color="var(--primary)" />
                  </div>
                </div>
              </div>
              <div className="px-6 py-2 mt-12">
                    <h2 className="text-[var(--text)] text-center font-bold text-[25px]">
                        I'm a <span className="text-[var(--primary)]">Customer</span></h2>
                        <p className="text-[15px] text-center mt-2 text-[var(--secondary-text)] ">
                Book appointments,explore salons, and enjoy our website services
              </p>
           <div className="flex flex-col mt-6 gap-3  w-full">
            <li className="text-[var(--secondary-text)]  text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)"  className="shrink-0" size={19} />
               Book appontment easily
            </li>
            <li className="text-[var(--secondary-text)] text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)" className="shrink-0" size={19} />
              Track your bookings
            </li>
            <li className="text-[var(--secondary-text)] text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)" className="shrink-0" size={19} />
              Save your favorite salon
            </li>
            <li className="text-[var(--secondary-text)]  text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)" className="shrink-0" size={19} />
              Exclusive offers & discounts
            </li>

            <Link href={'/signup/customer'} className="px-7 mt-3 mb-3 justify-center py-3 text-[var(--surface)] 
            items-center w-full flex text-[14px] gap-2 scale-100 hover:scale-105 transition-all duration-300
             rounded-[10px] bg-[var(--primary)]">
                  Continue as Customer
                  <BsArrowRight color="var(--surface)" size={18}/>
            </Link>
          </div>
              </div>
            </div>
            {/* salon owner section */}
            <div className="bg-[var(--surface)] p-2 rounded-[10px]">
              <div className="w-full relative flex justify-center">
                <Image
                  src={"/images/salon.jpg"}
                  className="object-cover  h-[300px] rounded-[10px]"
                  alt=""
                  width={800}
                  height={600}
                />
                <div className="absolute flex justify-center -bottom-10 w-[100px] h-[100px] rounded-full p-1 bg-[var(--surface)]">
                  <div className="bg-[var(--rose-gold)]/50 items-center flex justify-center w-[90px] h-[90px] rounded-full">
                    <FaStoreAlt size={50} color="var(--primary)" />
                  </div>
                </div>
               
              </div>
              <div className="px-6 py-2 mt-12">
                    <h2 className="text-[var(--text)] text-center font-bold text-[25px]">
                        I'm a <span className="text-[var(--primary)]">Salon Owner</span></h2>
                        <p className="text-[15px] text-center mt-2 text-[var(--secondary-text)] ">
                 Manage your salon,bookings,and grow your business
              </p>
              <div className="flex flex-col mt-6 gap-3  w-full">
            <li className="text-[var(--secondary-text)]  text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)"  className="shrink-0" size={19} />
               Mangae bookings & schedule
            </li>
            <li className="text-[var(--secondary-text)] text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)" className="shrink-0" size={19} />
              Showcase your services
            </li>
            <li className="text-[var(--secondary-text)] text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)" className="shrink-0" size={19} />
              Grow your salon business
            </li>
            <li className="text-[var(--secondary-text)]  text-[13px] gap-2 flex items-center">
              <MdCheckCircle color="var(--primary)" className="shrink-0" size={19} />
              Analytics & insights
            </li>

            <Link href={'/signup/salon-owner'} className="px-7 mt-3 mb-3 justify-center py-3 text-[var(--surface)] 
            items-center w-full text-[14px] flex gap-2 scale-100 hover:scale-105 transition-all duration-300
             rounded-[10px] bg-[var(--primary)]">
                   Continue as Salon Owner
                  <BsArrowRight color="var(--surface)" size={18}/>
            </Link>
          </div>
              </div>
            </div>
          </div>
        </div>
        <div className="col-span-3"></div>
      </div>

      <div className="grid grid-cols-2 gap-8 "></div>
    </section>
  );
}
