import BreadCrumb from "@/src/components/admin/ui/BreadCrumb";
import Card from "@/src/components/admin/ui/Card";
import Table from "@/src/components/admin/salon/Table";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "مدیریت سالن",
  description: "Generated by create next app",
};

export default function Blog() {
  return (
    <section>
      <BreadCrumb title="مدیریت سالن" activePage="مدیریت سالن ها" />
      <Card>
        <Table />
      </Card>
    </section>
  );
}
