import AboutSalon from "@/src/components/main/SingleSalon/AboutSalon";
import Gallery from "@/src/components/main/SingleSalon/Gallery";
import Header from "@/src/components/main/SingleSalon/Header";
import Info from "@/src/components/main/SingleSalon/Info";
import Reviews from "@/src/components/main/SingleSalon/Reviews";
import Service from "@/src/components/main/SingleSalon/Service";
import Stylist from "@/src/components/main/SingleSalon/Stylist";
import BreadCrumb from "@/src/components/main/ui/BreadCrumb";
import { Metadata } from "next";

type Props = {
  params: Promise<{ slug: string }>;
};

export const metadata: Metadata = {
  title: "salon number one",
  description: "Generated by create next app",
};

export default async function Page({ params }: Props) {
  const { slug } = await params;
  return (
    <div className="container-c  mt-30 mb-10">
      <BreadCrumb
        items={[
          { label: "Home", href: "/" },
          { label: "Salons", href: "/salons" },
          { label: "Salon Number one" },
        ]}
      />
      <Header />
      <Service/>
      <AboutSalon/>
      <Stylist/>
      <Gallery/>
      <Reviews/>
      <Info/>
    </div>
  );
}
