import Analytic from "@/src/components/main/contact-us/Analytic";
import Benefit from "@/src/components/main/contact-us/Benefit";
import ContactSec from "@/src/components/main/contact-us/ContactSec";
import Faq from "@/src/components/main/contact-us/Faq";
import Header from "@/src/components/main/contact-us/Header";
import { Metadata } from "next";



export const metadata: Metadata = {
  title: "contact us",
  description: "Generated by create next app",
};



export default function Page(){
    return(
      <section>
          <Header/> 
          <Benefit/>
          <ContactSec/>
          <Faq/>
          <Analytic/>
      </section>
    )
}